version: '3.8'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - nextjs-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
