name: Vercel Deploy

on:
  push:
    branches:
      - master  # or your deploy branch like 'develop', 'production', etc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Trigger Vercel Deploy Hook
        run: |
          curl -X POST "${{ secrets.VERCEL_DEVELOP_DEPLOY_HOOK }}"
