name: Vercel Deploy

on:
  push:
    branches:
      - master  # or your deploy branch like 'develop', 'production', etc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }} \
          --org ${{ secrets.VERCEL_ORG_ID }} \
          --project ${{ secrets.VERCEL_PROJECT_ID }}
